### ISSUE TITLE
Leftover child processes when using Lwt.pick

### ISSUE THREAD

**Issue by hcarty** [ivg/parallel#5]
The following example (saved as `par.ml`, in this example) will leave a stray `par.native` running after the main program exits.

``` ocaml
let f x =
  Lwt_unix.sleep x

let () =
  Parallel.init ();
  Lwt_main.run @@ Lwt.pick [
    Parallel.run f 0.1;
    Parallel.run f 1.0;
  ]
```

built with

```
ocamlbuild -use-ocamlfind -package lwt-parallel par.native
```

**Comment by ivg** [comment]
`par.native` is the executable itself :)

**Comment by hcarty** [comment]
There are multiple par.native instances running during execution of the program. The child processes are not killed when their Lwt thread is canceled.

So while you are correct, there shouldn't be any left running after the main process exits.

**Comment by ivg** [comment]
Do you mean, that there is a process left after the process exits?

**Comment by hcarty** [comment]
@ivg yes, that's what happens for me in the example above. The forked child process remains after the parent process exits.

**Comment by ivg** [comment]
ah, sorry, I misread you the first time. Will take a look. I do remember that we had this problem in the original program from which this library was forked. Maybe I should bump the fix from the upstream.
Thanks for noticing this!

**Comment by rand00** [comment]
I even get a leftover process when compiling and running the following:

``` ocaml
let _ = Parallel.init ()
```

Also it seems that there exist the same amount of leftover processes after execution of program as the times `Parallel.run` is called.

**Comment by rand00** [comment]
If someone need a quickfix like I do - I'm wrapping my ocaml program with the following script. This will of course not be a good idea to run if your program hasn't got a unique name (:

``` bash
#! /bin/bash

PN=$1; shift 1

./$PN $*
retc=$?
killall $PN
exit $retc
```
